spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/client_account?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=20000
#    driverClassName: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME:pcdbuser}
    password: ${MYSQL_PWD:pcdbuser}
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none

#accountIfc:
#  class:com.azlan.test.clientaccount.service.ifc.AccountServiceIfc


logging:
  level:
    org.springframework: DEBUG
    com.azlan.test: DEBUG
