spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/client_account?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=20000
    username: ${MYSQL_USERNAME:pcdbuser}
    password: ${MYSQL_PWD:pcdbuser}
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: DEBUG
    com.azlan.test: DEBUG
